### ISSUE TITLE
Add auto versioning 

### ISSUE THREAD

**Issue by rhtnr** [rhtnr/Cake.SonarResults#1]
You can replicate build and revision wildcards by implementing [roslyn's version pattern logic](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/Core/Portable/VersionHelper.cs#L187-L202) in pure MSBuild:

```xml
<PropertyGroup>
  <Build>$([System.DateTime]::op_Subtraction($([System.DateTime]::get_Now().get_Date()),$([System.DateTime]::new(2000,1,1))).get_TotalDays())</Build>
  <Revision>$([MSBuild]::Divide($([System.DateTime]::get_Now().get_TimeOfDay().get_TotalSeconds()), 2).ToString('F0'))</Revision>
  <Version>1.2.$(Build).$(Revision)</Version>
</PropertyGroup>
```

_Originally posted by @dasMulli in https://github.com/dotnet/cli/issues/6923#issuecomment-354095128_

**Comment by dasMulli** [comment]
That was meant more as a joke than an actual recommendation 😱😱😱

There's also git-based versions i'd rather recommend.. https://github.com/AArnott/Nerdbank.GitVersioning, https://github.com/dasMulli/SimpleGitVersion

**Comment by rhtnr** [comment]
> That was meant more as a joke than an actual recommendation 😱😱😱
> 
> There's also git-based versions i'd rather recommend.. https://github.com/AArnott/Nerdbank.GitVersioning, https://github.com/dasMulli/SimpleGitVersion

@dasMulli thank you for the git based versions. But I was actually looking for git commit based versioning. I couldn't find any. But I found that that the recommendation works for me even though you meant it more as a joke
