### ISSUE TITLE
Missing RestSharp

### ISSUE THREAD

**Issue by CRuppert** [rhtnr/Cake.SonarResults#5]
After running a build, in the same step I invoke the SonarResults bit.
step content in brief:
```
SonarBegin
MSBuild
SonarEnd
SonarQubeResults
```

Log output:
```
Creating a Sonar Task Retriever Client
An error occurred when executing task 'Inspect Code'.
Error: One or more errors occurred.
        Could not load file or assembly 'RestSharp, Version=106.0.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75' or one of its dependencies. The system cannot find the file specified.
```

Just because, i attempted to add the appropriate dependency to my cake's packages.config file, no luck.
Manually copying the .net standard 2.0 restsharp dll into the addin's lib directory allowed it to proceed

**Comment by CRuppert** [comment]
@rhtnr  have you abandoned this repo?

**Comment by rhtnr** [comment]
@CRuppert I don't have the time now to make immediate changes. Please feel free to contribute

**Comment by CRuppert** [comment]
I'd be happy to. I am glad to know this is not abandoned and PR's will be welcome. :) I've contributed to projects before that PR's sat forever. Hence me asking. 

Take care!

**Comment by CRuppert** [comment]
By forcing cake to install the module dependencies using &loaddependencies=true as is shown here:
#addin "nuget:?package=Cake.SonarResults&version=0.3.7333.37604&loaddependencies=true"
it will force cake to install child deps, resolving this problem.
