### ISSUE TITLE
Error - Cannot retrive SonarQube Task ?

### ISSUE THREAD

**Issue by kzkzg** [rhtnr/Cake.SonarResults#7]
```
Retrieving task status from http://localhost:9000/api/ce/task?id=xxxxxxxxxxxxxxxxx [POST]
An error occured while retrieving Task Status from SonarQube - SonarQube Task cannot be retrieved
```

Please help fixing this error. When i request this url over Postman or web browser I have proper response.

**Comment by rhtnr** [comment]
Im not actively contributing to the repo anymore. Is there anyway you could debug this? Its unlikely that this is caused by the addin

**Comment by iisystems** [comment]
I have the same issue.  @kzkzg did you find a solution to this?
